---
- name: Task to check reboot
  hosts: node1
  tasks:
    - name: Check uptime
      shell: "uptime | awk '{ print $3}' | cut -d: -f1"
      register: res

    - debug:
        msg: Uptime is {{ res.stdout }}

    - name: reboot the server 
      shell: init 6
#      when:  '{{ res.stdout }} > 1'
      async: 30
      poll: 1
      ignore_errors: true
    
 #    - name: Pause for 180 secs
 #     pause:
 #       minutes: 3

    - name: Check if all the systems responding to ssh
      local_action:
        module: wait_for
          host={{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}
          port=22
          search_regex=OpenSSH
          delay=15
          timeout=300
          state=started

