---
- name: Task to check reboot
  hosts: all
  tasks:
    - name:  Reboot Servers
      reboot:
       msg: "Rebooting  Servers"
       connect_timeout: 5
       reboot_timeout: 300
       pre_reboot_delay: 0
       post_reboot_delay: 30
       test_command: uptime
      register: test
#      #when: reboot_required_file.stat.exists and (ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian')
#        register: reboot_started_ubuntu
#      ignore_errors: true
#
#    - name: Pause for 180 secs
#      pause:
#        minutes: 3
    - debug:
        msg: "{{ test.rebooted }}"

    - name: Check if all the systems responding to ssh
      local_action:
        module: wait_for
          host={{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}
          port=22
          search_regex=OpenSSH
          delay=15
          timeout=300
         state=started
