---
- name: Get SSL Info
  hosts: node1
  tasks:
    - name: Get information on generated certificate
      openssl_certificate_info:
        path: /tmp/example.crt
      register: result

    - name: Dump information
      debug:
        var: result
